version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - celery-worker
    env_file:
      - .prod.env

  redis:
    image: redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    
  nginx:
    image: nginx
    volumes:
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - 80:80
    depends_on:
      - web