version: '3'

services:
  db:
    image: postgres:14.8-alpine3.18 
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "-w", "3", "-b", "0.0.0.0:8000", "core.wsgi:application"]
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - celery-worker
    env_file:
      - .env.prod
    restart: always

  redis:
    image: redis:7.0.11-alpine

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
    - .env.prod
    restart: always
    
  nginx:
    image: nginx
    volumes:
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - 80:80
    depends_on:
      - web
