# Generated by Django 4.2.2 on 2023-06-16 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_options_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="main_image",
        ),
    ]
