# Generated by Django 4.2.2 on 2023-06-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="Slug ID",
            ),
        ),
    ]
